// Mirrors the voice table in kokoro-js 1.2.1 (English voices only; kokoro-js rejects others).
// Kept separate so the popup doesn't need to import the TTS library.
export const VOICES = {
  af_heart: { name: 'Heart', lang: 'en-us', gender: 'Female', grade: 'A' },
  af_bella: { name: 'Bella', lang: 'en-us', gender: 'Female', grade: 'A-' },
  af_nicole: { name: 'Nicole', lang: 'en-us', gender: 'Female', grade: 'B-' },
  af_aoede: { name: 'Aoede', lang: 'en-us', gender: 'Female', grade: 'C+' },
  af_kore: { name: 'Kore', lang: 'en-us', gender: 'Female', grade: 'C+' },
  af_sarah: { name: 'Sarah', lang: 'en-us', gender: 'Female', grade: 'C+' },
  af_alloy: { name: 'Alloy', lang: 'en-us', gender: 'Female', grade: 'C' },
  af_nova: { name: 'Nova', lang: 'en-us', gender: 'Female', grade: 'C' },
  af_sky: { name: 'Sky', lang: 'en-us', gender: 'Female', grade: 'C-' },
  af_jessica: { name: 'Jessica', lang: 'en-us', gender: 'Female', grade: 'D' },
  af_river: { name: 'River', lang: 'en-us', gender: 'Female', grade: 'D' },
  am_fenrir: { name: 'Fenrir', lang: 'en-us', gender: 'Male', grade: 'C+' },
  am_michael: { name: 'Michael', lang: 'en-us', gender: 'Male', grade: 'C+' },
  am_puck: { name: 'Puck', lang: 'en-us', gender: 'Male', grade: 'C+' },
  am_echo: { name: 'Echo', lang: 'en-us', gender: 'Male', grade: 'D' },
  am_eric: { name: 'Eric', lang: 'en-us', gender: 'Male', grade: 'D' },
  am_liam: { name: 'Liam', lang: 'en-us', gender: 'Male', grade: 'D' },
  am_onyx: { name: 'Onyx', lang: 'en-us', gender: 'Male', grade: 'D' },
  am_santa: { name: 'Santa', lang: 'en-us', gender: 'Male', grade: 'D-' },
  am_adam: { name: 'Adam', lang: 'en-us', gender: 'Male', grade: 'F+' },
  bf_emma: { name: 'Emma', lang: 'en-gb', gender: 'Female', grade: 'B-' },
  bf_isabella: { name: 'Isabella', lang: 'en-gb', gender: 'Female', grade: 'C' },
  bf_alice: { name: 'Alice', lang: 'en-gb', gender: 'Female', grade: 'D' },
  bf_lily: { name: 'Lily', lang: 'en-gb', gender: 'Female', grade: 'D' },
  bm_fable: { name: 'Fable', lang: 'en-gb', gender: 'Male', grade: 'C' },
  bm_george: { name: 'George', lang: 'en-gb', gender: 'Male', grade: 'C' },
  bm_lewis: { name: 'Lewis', lang: 'en-gb', gender: 'Male', grade: 'D+' },
  bm_daniel: { name: 'Daniel', lang: 'en-gb', gender: 'Male', grade: 'D' },
};
